### ISSUE TITLE
Export of highlights broken due to change in kindle file format?

### ISSUE THREAD

**Issue by elkrause** [sawyerh/highlight-utils#7]
Hi! I'm appying your script, but I only get the header information of the book, no highlights. Are there some changes in the kindle file format?

Please find here my test export:
[test2.zip](https://github.com/sawyerh/highlight-utils/files/4497191/test2.zip)

**Comment by sawyerh** [comment]
@elkrause Hey there, thanks for reporting this. I'll try to dig into this more in the next few weeks.

**Comment by sawyerh** [comment]
I was unfortunately unable to open the attachment in the zipped email so wasn't able to reproduce this issue. It's possible that you're running into this issue (https://github.com/sawyerh/kindle-email-to-json/issues/1). If you're able to share the HTML contents of the Kindle attachment, I'm happy to take a closer look.
